site_name: messeage queue
site_url: https://cloud-monitor.github.io/message_queue
site_description: queue stubs
site_author: Hoa Ngo

repo_url: https://github.com/cloud-guru/message_queue
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
nav:
    - Index: index.md
    - INTRODUCTION:
        - Issue describe: issue/README.md
    - TECHNICAL RESEARCH:
        - Kafka: issue/need_review/Kafka/README.md
        - Rabbit_mq: issue/need_review/Rabbit/README.md
        - Qpid_dispatch_route: issue/need_review/Qdr/README.md
    - BLUEPRINT:
        - Propose: issue/propose/README.md
        - Start: issue/start/README.md
        - In process: issue/in_process/README.md
        - Need review: issue/need_review/README.md
        - Sloved: issue/solved/README.md
    - ABOUT:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/license.md

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - admonition
